sudo: required

language: elixir

services:
  - docker

env:
  - MIX_ENV=test
  
before_install:
  - sudo apt-get update && sudo apt install -y crul
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  - echo "PATH=~/.cargo/bin:$PATH" >> ~/.profile && source ~/.profile
  - docker run --rm -name mssql -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=some!Password' -p 127.0.0.1:1433:1433 -v $(pwd):/opt/src -d microsoft/mssql-server-linux 
  - docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P some!Password -d master -i /opt/src/setup.sql

script:
  - mix do deps.get,compile
  - mix test