sudo: required

language: elixir

elixir: '1.8'

otp_release: '21.3'

services:
  - docker

env:
  - MIX_ENV=test ACCEPT_EULA=y MSSQL_SA_PASSWORD=some!Password

before_install:
  - sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
  - sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"
  - sudo apt-get update 
  - sudo apt-get install -y openssl mssql-tools unixodbc-dev mssql-server
  - sudo /opt/mssql/bin/mssql-conf -n setup accept-eula
  # - sudo systemctl restart mssql-server
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d master -i $TRAVIS_BUILD_DIR/setup.sql

script:
  - source $HOME/.cargo/env
  - export PATH=$PATH:/opt/mssql-tools/bin
  - mix deps.get
  - mix test