name: Elixir TDS

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:${{ matrix.mssql_version }}
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: some!Password
        ports:
          - 1433:1433

    strategy:
      matrix:
        mssql_version: ["2017-latest", "2019-latest"]


    env:
      ACCEPT_EULA: Y

    steps:
      - name: Install MsSql Client Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.9.4 # Define the elixir version [required]
          otp-version: 21.3 # Define the OTP version [required]
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: |
          export PATH="/opt/mssql-tools/bin:$PATH"
          mix test
